### ISSUE TITLE
Question: best practises

### ISSUE THREAD

**Issue by skoch13** [henriqueinonhe/promises-training#38]
Thank you for this awesome project! Just a question: Will best practices or solutions be added eventually? Discussions might be a perfect place for such a thing.

**Comment by henriqueinonhe** [comment]
Although I forgot to mention it on the README 😅 , this repo has all the solutions (this is one of the reasons we ask people to install via the installer, as it "erases" the solutions before installing). E.g. https://github.com/henriqueinonhe/promises-training/blob/v2.0.0/src/exercises/concrete/extractingResolvers/exercise.ts

However, these solutions are not necessarily the best ones, so yeah, it would be nice to have discussions around exercises.

I've enabled the discussions feature for this repo, so feel free to open discussions if you'd like.

**Comment by henriqueinonhe** [comment]
I'll leave the issue open until I update the README

**Comment by henriqueinonhe** [comment]
Fixed on https://github.com/henriqueinonhe/promises-training/releases/tag/v2.0.1
