### ISSUE TITLE
Parallel Collect Retry's Readme typo

### ISSUE THREAD

**Issue by spd789562** [henriqueinonhe/promises-training#39]
In this line, I believe it should be 
> is similar to the `concrete/parallelCollectErrors` exercise

https://github.com/henriqueinonhe/promises-training/blob/9271173fb6fa62dfa7b1c4e7354258bb509278e3/src/exercises/concrete/parallelCollectRetry/README.md?plain=1#L5

**Comment by henriqueinonhe** [comment]
Yes, you're correct, thanks for reporting!

**Comment by henriqueinonhe** [comment]
Fixed on https://github.com/henriqueinonhe/promises-training/releases/tag/v2.0.1
